server: 
  port: 9000
spring:  
  kafka: 
    #listener:
      #ack-mode: manual
    consumer:
       enable-auto-commit: true #false
       bootstrap-servers: localhost:9092
       group-id: group_id
       auto-offset-reset: latest
    producer:
        bootstrap-servers: localhost:9092
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: greetings
